services:
  - type: web
    name: api-gateway
    env: docker
    dockerfilePath: api-gateway/Dockerfile
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis
          property: connectionString
      - key: RABBITMQ_URL
        value: amqp://rabbitmq:5672
  - type: web
    name: identity-service
    env: docker
    dockerfilePath: identity-service/Dockerfile
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis
          property: connectionString
      - key: RABBITMQ_URL
        value: amqp://rabbitmq:5672
  - type: web
    name: post-service
    env: docker
    dockerfilePath: post-service/Dockerfile
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis
          property: connectionString
      - key: RABBITMQ_URL
        value: amqp://rabbitmq:5672
  - type: web
    name: media-service
    env: docker
    dockerfilePath: media-service/Dockerfile
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis
          property: connectionString
      - key: RABBITMQ_URL
        value: amqp://rabbitmq:5672
  - type: web
    name: search-service
    env: docker
    dockerfilePath: search-service/Dockerfile
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis
          property: connectionString
      - key: RABBITMQ_URL
        value: amqp://rabbitmq:5672
  - type: redis
    name: redis
    plan: free
  - type: worker
    name: rabbitmq
    env: docker
    dockerfilePath: rabbitmq/Dockerfile
    plan: free